# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # configure a Extended storage for mysql data
  config.extended_storage.enabled = true
  config.extended_storage.location = "virtualdrive.vdi"
  config.extended_storage.size = 5000
  config.extended_storage.mountname = 'mysql'
  config.extended_storage.filesystem = 'ext4'
  config.extended_storage.mountpoint = '/var/lib/mysql'
  config.extended_storage.volgroupname = 'vg_os'
  config.extended_storage.mountname = 'root'

end
